site_name: book.koad.sh
site_url: https://book.koad.sh
site_author: koad
site_description: >-
  The results of years of broken thoughts.

# Repository
repo_name: documentation
repo_url: https://github.com/koad/documentation
edit_uri: ""
docs_dir: src/

extra_css:
  - stylesheets/extra.css

# Copyright
copyright: Copyright &copy; 2022


# Configuration
theme:

  name: material

  logo: assets/avatar.png


  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      accent: koad
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      accent: koad-dark
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github-alt


# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/koad
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kingofalldata
      name: kingofalldata on Twitter
    - icon: fontawesome/brands/keybase
      link: https://keybase.io/koad/sigchain
  # generator: false

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - attr_list
  - md_in_html

nav:
  - Home: 
    - index.md
  - Getting started:
    - getting-started/index.md
    - getting-started/the-game-plan.md
    - getting-started/prepare-yourself.md
    - getting-started/picking-your-username.md
    - getting-started/spawning-a-keybase-identity.md
    - getting-started/securing-your-keybase-identity.md
    - getting-started/create-your-first-keybase-team.md
    - getting-started/invite-your-mother-to-keybase.md
    - getting-started/hallmarks-of-a-scam.md
    - getting-started/block-email-scams.md
    - getting-started/block-internet-scams.md
    - getting-started/block-phishing-scams.md
    - getting-started/block-telephone-scams.md
    - getting-started/block-financial-scams.md
    - getting-started/secure-your-family.md
    - getting-started/secure-your-surroundings.md
    - getting-started/secure-your-files-and-folders.md
    - getting-started/secure-your-windows-desktop.md
    - getting-started/secure-your-android.md
    - getting-started/secure-your-iphone.md
    - getting-started/secure-your-mac.md
    - getting-started/secure-your-television.md
    - getting-started/secure-your-smart-speaker.md
    - getting-started/in-review.md
    - getting-started/sharing-is-caring.md

  - Setup:
    - setup/index.md
    - Ensuring data privacy: setup/ensuring-data-privacy.md
    - Year Zero: setup/year-zero.md
    - Aquire some hardware: setup/aquire-some-hardware.md
    - setup/prepare-your-kingdom.md
    - setup/picking-your-domain-name.md
    - setup/lets-encrypt-wildcard-cert.md
    - setup/understanding-the-matrix.md
    - setup/installing-the-matrix.md
    - setup/invite-your-loved-ones.md
    - setup/create-your-first-space.md
    - setup/create-your-first-channels.md
    - setup/understanding-sandstorm.md
    - setup/installing-sandstorm.md
    - setup/create-your-first-sandbox.md
    - setup/create-state-database.md
  - Books:
    - reference/books/index.md
    - The Book of the Way: reference/books/lao-tzu-the-book-of-the-way.md
    - Getting Things Done (GTD): reference/books/gtd-getting-things-done.md
    - New Local Economy: reference/books/new-local-economy.md
    - The Amazing Power of Deliberate Intent: reference/books/the-amazing-power-of-deliberate-intent.md
    - reference/books/digital-minimalism.md
  - Reference:
    - reference/index.md
    - Topic Coverage: checklists/kingdom-general.md
    - koad:io entity: reference/koad-io-entity.md
    - Introduction: introduction.md 
    - koad.live: koad.live.md
    - koad was here: whoami.md
    - tags.md
    - getting-started/desktop.md
    - insiders/index.md
    - setup/components.md
    - reference/generate-keybase-gpg-key.md
    - reference/a-new-diet-for-my-broken-body.md
    - reference/custom-customized-customizations.md
    - reference/essential-nutrients-for-human.md
    - reference/four-freedoms-of-open-source-producers.md
    - reference/koads-entity-state-dbs.md
    - reference/manifest-heaven-on-earth.md
    - reference/passwordless-ssh.md
    - reference/thy-self.md
    - reference/you-name-it.md
    - scratch-pad/managing-docker.md
    - scratch-pad/minimal-browser-app-window.md
    - reference/mp-positions.md
    - reference/koad-io/index.md
    - reference/koad-io/commands.md
    - scratch-pad/books-about-medical-things.md
    - scratch-pad/ecoincore-basic-components.md
    - scratch-pad/preparing-new-vps-from-scratch.md
    - scratch-pad/privateness-apr-11-2022.md
    - scratch-pad/some-sort-of-email-solution-for-local-users.md
  - Components:
    - components/ability-to-identify-limiting-beliefs.md
    - components/audio-and-music.md
    - components/cache-box.md
    - components/calendar-and-contacts.md
    - components/cloud-computing.md
    - components/creation-station.md
    - components/cryptographic-proofs.md
    - components/desktop-enviroments.md
    - components/digital-social-gathering.md
    - components/digtial-networks.md
    - components/email-with-catchall-enabled.md
    - components/files-and-folders.md
    - components/home-server.md
    - components/inbox.md
    - components/key-sets-and-tool-chains.md
    - components/mobile-experience.md
    - components/photo-albums.md
    - components/physical-automation.md
    - components/positive-mental-attitude.md
    - components/private-communication.md
    - components/projects-and-support-material.md
    - components/service-hosting.md
    - components/signing-authorities.md
    - components/telephone-fax-and-sms.md
    - components/user-accounts.md
    - components/virtualization.md
    - components/visual-entertainment.md
    - components/willingness-to-accept-change.md
    - components/domain-names-and-registrars.md
    - components/package-registry.md
  - Repositories:
    - repo/simple-qrcode-image-api.md
  - Cheat Sheets:
    - cheatsheets/index.md    
    - cheatsheets/meteor-js/index.md
    - cheatsheets/nginx/index.md
    - cheatsheets/node-volume-manager/index.md
    - cheatsheets/uncomplicated-firewall/index.md
    - scratch-pad/install-sandstorm-via-docker.md
    - scratch-pad/keyboard-shortcuts.md
    - cheatsheets/apt-get-thinks-i-no-longer-require.md
    - cheatsheets/archive-an-entire-site.md
    - cheatsheets/available-software-licences.md
    - cheatsheets/canada-ecoin.md
    - cheatsheets/clearing-consoles.md
    - cheatsheets/daily-worksheet.md
    - cheatsheets/designing-print-with-css.md
    - cheatsheets/docker-randomness.md
    - cheatsheets/faith-over-fear.md
    - cheatsheets/frequently-used-commands-alice.md
    - cheatsheets/frequently-used-commands-pandora.md
    - cheatsheets/in-gnome-terminal-window.md
    - cheatsheets/jitsi-self-hosting.md
    - cheatsheets/mongo-db.md
    - cheatsheets/nodejs-signale-logger.md
    - cheatsheets/opendns.md
    - cheatsheets/portainer-standalone.md
    - cheatsheets/progressive-web-apps.md
    - cheatsheets/sandbox-a-browser-awindow-within-a-new-data-dir.md
    - cheatsheets/why-i-choose-spotify-as-a-port-of-a-whole-and-balanced-diet.md
    - cheatsheets/matrix/index.md
    - cheatsheets/meteor-js/ddp.md
    - cheatsheets/meteor-js/dot-env.md
    - cheatsheets/meteor-js/dot-meteor-slash-packages.md
    - cheatsheets/meteor-js/meteor-vs-the-world.md
    - cheatsheets/meteor-js/randomness.md
    - cheatsheets/async-javascript-self-loading-function.md
    - cheatsheets/basic-training.md
    - cheatsheets/bourn-again-scripting.md
    - cheatsheets/braille-cursors.md
    - cheatsheets/decentralized-social-proofs.md
    - cheatsheets/koad-io-template-helpers.md
    - cheatsheets/meteor-js/create-new-user.md
    - cheatsheets/meteor-js/roles.md
    - cheatsheets/meteor-js/shell.md