site_name: docs.koad.sh
site_url: https://docs.koad.sh
site_author: koad
site_description: >-
  The results of years of broken thoughts.

# Repository
repo_name: documentation
repo_url: https://github.com/koad/documentation
edit_uri: ""
docs_dir: src/

extra_css:
  - stylesheets/extra.css

# Copyright
copyright: Copyright &copy; 2022


# Configuration
theme:

  name: material

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      accent: koad
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      accent: koad-dark
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github-alt


# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/koad
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kingofalldata
      name: kingofalldata on Twitter
    - icon: fontawesome/brands/keybase
      link: https://keybase.io/koad/sigchain
  # generator: false

nav:
  - Home: index.md
  - Getting started:
    - Introduction: introduction.md 
    - Component Pieces: components/README.md
    - Prerequisites: prerequisites/README.md
    - Year Zero: year-zero.md
  - Setup:
    - Ensuring data privacy: setup/ensuring-data-privacy.md
  - Reference:
    - reference/index.md
  - Insiders:
    - insiders/index.md
  - Blog:
    - blog/index.md
    - 2022:
      - blog/2022-March-13th-upstart.md
