site_name: docs.koad.sh
site_url: https://docs.koad.sh
site_author: koad
site_description: >-
  The results of years of broken thoughts.

# Repository
repo_name: documentation
repo_url: https://github.com/koad/documentation
edit_uri: ""
docs_dir: src/

extra_css:
  - stylesheets/extra.css

# Copyright
copyright: Copyright &copy; 2022


# Configuration
theme:

  name: material

  logo: assets/avatar.png


  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      accent: koad
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      accent: koad-dark
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github-alt


# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/koad
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kingofalldata
      name: kingofalldata on Twitter
    - icon: fontawesome/brands/keybase
      link: https://keybase.io/koad/sigchain
  # generator: false

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - attr_list
  - md_in_html

nav:
  - Home: 
    - index.md
  - Getting started:
    - getting-started/index.md
    - getting-started/the-game-plan.md
    - getting-started/prepare-yourself.md
    - getting-started/picking-your-username.md
    - getting-started/spawning-a-keybase-identity.md
    - getting-started/securing-your-keybase-identity.md
    - getting-started/create-your-first-keybase-team.md
    - getting-started/invite-your-mother-to-keybase.md
    - getting-started/hallmarks-of-a-scam.md
    - getting-started/block-email-scams.md
    - getting-started/block-internet-scams.md
    - getting-started/block-phishing-scams.md
    - getting-started/block-telephone-scams.md
    - getting-started/block-financial-scams.md
    - getting-started/secure-your-family.md
    - getting-started/secure-your-surroundings.md
    - getting-started/secure-your-files-and-folders.md
    - getting-started/secure-your-windows-desktop.md
    - getting-started/secure-your-android.md
    - getting-started/secure-your-iphone.md
    - getting-started/secure-your-mac.md
    - getting-started/secure-your-television.md
    - getting-started/secure-your-smart-speaker.md
    - getting-started/in-review.md
    - getting-started/sharing-is-caring.md

  - Setup:
    - setup/index.md
    - Ensuring data privacy: setup/ensuring-data-privacy.md
    - Year Zero: setup/year-zero.md
    - Aquire some hardware: setup/aquire-some-hardware.md
    - setup/prepare-your-kingdom.md
    - setup/picking-your-domain-name.md
    - setup/lets-encrypt-wildcard-cert.md
    - setup/understanding-the-matrix.md
    - setup/installing-the-matrix.md
    - setup/invite-your-loved-ones.md
    - setup/create-your-first-space.md
    - setup/create-your-first-channels.md
    - setup/understanding-sandstorm.md
    - setup/installing-sandstorm.md
    - setup/create-your-first-sandbox.md
    - setup/create-state-database.md
  - Books:
    - reference/books/index.md
    - The Book of the Way: reference/books/lao-tzu-the-book-of-the-way.md
    - Getting Things Done (GTD): reference/books/gtd-getting-things-done.md
    - New Local Economy: reference/books/new-local-economy.md
    - The Amazing Power of Deliberate Intent: reference/books/the-amazing-power-of-deliberate-intent.md
    - reference/books/digital-minimalism.md
  - Reference:
    - reference/index.md
    - Topic Coverage: checklists/kingdom-general.md
    - koad:io entity: reference/koad-io-entity.md
    - Introduction: introduction.md 
    - koad.live: koad.live.md
    - koad was here: whoami.md
    - tags.md
    - getting-started/desktop.md
    - insiders/index.md
    - setup/components.md
  - Cheat Sheets:
    - cheatsheets/index.md    
    - cheatsheets/meteor-js/index.md
    - cheatsheets/nginx/index.md
    - cheatsheets/node-volume-manager/index.md
    - cheatsheets/uncomplicated-firewall/index.md
    - reference/generate-keybase-gpg-key.md
    - scratch-pad/install-sandstorm-via-docker.md
    - scratch-pad/keyboard-shortcuts.md
