site_name: book.koad.sh
site_url: https://book.koad.sh
site_author: koad
site_description: >-
  The results of years of broken thoughts.

# Repository
repo_name: documentation
repo_url: https://github.com/koad/documentation
edit_uri: ""
docs_dir: src/

extra_css:
  - stylesheets/extra.css

# Copyright
copyright: Copyright &copy; 2023


# Configuration
theme:

  name: material

  logo: assets/avatar.png


  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      accent: koad
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      accent: koad-dark
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github-alt

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/koad
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kingofalldata
      name: kingofalldata on Twitter
    - icon: fontawesome/brands/keybase
      link: https://keybase.io/koad/sigchain
  # generator: false

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: 
    - index.md
  - Getting started:
    - getting-started/index.md
    - getting-started/hallmarks-of-a-scam.md
    - getting-started/block-email-scams.md
    - getting-started/block-telephone-scams.md
    - getting-started/block-financial-scams.md
    - getting-started/secure-your-surroundings.md
    - getting-started/secure-your-computer.md
    - getting-started/secure-your-phone.md
    - getting-started/secure-your-smart-speaker.md
    - getting-started/secure-your-family.md
    - getting-started/picking-your-username.md
    - getting-started/learning-to-search.md
    - getting-started/in-review.md
    - getting-started/sharing-is-caring.md

  - Mindspace 101:
    - mindspace/index.md
    - mindspace/david-allen.md
    - mindspace/dr-joe-dispenza.md
    - mindspace/ester-hicks.md

  - Blockchain 101:
    - blockchain/index.md
    - blockchain/how-to-stay-safe.md
    - blockchain/common-blockchain-terms.md
    - blockchain/what-is-a-fork.md
    - blockchain/what-is-a-mainnet.md
    - blockchain/what-is-a-protocol.md
    - blockchain/what-is-a-sidechain.md
    - blockchain/what-is-atomic.md
    - blockchain/what-is-a-wallet.md
    - blockchain/what-is-a-whitepaper.md
    - blockchain/what-are-bips.md
    - blockchain/what-is-consensus.md
    - blockchain/what-is-decentralized.md
    - blockchain/what-is-erc.md
    - blockchain/what-is-fungible.md
    - blockchain/what-is-public-key-infrastructure.md
    - blockchain/what-is-supply.md
    - blockchain/what-is-mining.md
    - blockchain/proof-of-proof.md
    - blockchain/attacking-the-blockchain.md
    - blockchain/mining-the-blockchain.md

  - Invite Only:
    - invite-only/index.md
    
    - invite-only/hitchhiking-the-digital-highway.md
    - invite-only/digital-hitchhikers-toolkit.md

    - invite-only/reimagining-online-communities.md
    - invite-only/future-of-digital-communities.md
    - invite-only/building-trust-and-authenticity.md

    - invite-only/sovereignty-proofs-and-currency.md
    - invite-only/investing-in-each-other.md
    - invite-only/community-currencies.md

    - invite-only/the-power-of-invitation.md
    - invite-only/the-power-of-perception.md
    - invite-only/trust-is-key.md

    - invite-only/conclusion.md
